name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Dir
      run: dir Configuration.Database\bin\Release\netcoreapp3.1
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Ng Vers
      run: nuget ? v
      
    - name: Add Source
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/KloderGit/index.json" -UserName KloderGit -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Push
      run: dotnet nuget push Configuration.Database\bin\Release\Configuration.Database.1.0.0.nupkg -k ${{ secrets.GITHUB_TOKEN }}  -s https://nuget.pkg.github.com/KloderGit/Configuration.Database/index.json


#    - name: Nuget Push
#      run: nuget push "Configuration.Database\bin\Release\Configuration.Database.1.0.0.nupkg" -Source "GitHub"

#    - name: Add GPR Source using nuget.exe
#      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/KloderGit/index.json -Username KloderGit -Password ${{ secrets.GITHUB_TOKEN }} 
    
#    - name: nuget push
#      run: nuget push Configuration.Database\bin\Release\*.nupkg -source "GPR" -SkipDuplicate
