name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Publish to Package
      run: dotnet nuget push "bin/Release/Configuration.Database.1.0.0.nupkg" --source "github"
